name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure Git
        uses: actions/configure-pages@v3
        with:
          user.email: ${{ secrets.GIT_EMAIL }}
          user.name: ${{ secrets.GIT_NAME }}
      - name: Install dependencies
        run: npm install
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
