name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          NAME: ${{ secrets.NAME }}
          run: |
            git config --global user.email "$EMAIL"
            git config --global user.name "$NAME"
