name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Install dependencies
        run: npm install
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
